import type { Metadata } from "next";
import { Manrope, Geist } from "next/font/google";
import "./globals.css";
import DashboardLayout from "@/components/dashboardLayout";
import SideBarSwitch from "@/components/sidebarSwitch";
import DashboardNavbar from "@/components/dashboardNavbar";
import { cn } from "@/lib/utils";
import { SearchProvider } from "../context/SearchContext";
import { RoleProvider } from "../context/RoleContext";
import { TransactionsProvider } from "../context/TransactionContext";
import { UserProvider } from "../context/UserContext";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["800", "700", "600", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        manrope.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full">
        <SearchProvider>
          <UserProvider>
            <RoleProvider>
              <TransactionsProvider>
                <DashboardLayout>
                  <DashboardLayout.Header>
                    <DashboardNavbar />
                  </DashboardLayout.Header>
                  <DashboardLayout.Sidebar>
                    <SideBarSwitch />
                  </DashboardLayout.Sidebar>
                  {children}
                </DashboardLayout>
              </TransactionsProvider>
            </RoleProvider>
          </UserProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
